worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;

    # Chỉ định nghĩa các service backend đang chạy trong Docker
    upstream iam_service {
        server iam-service:3001;
    }

    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index login.html index.html;
        }

        # Chuyển hướng các request bắt đầu bằng /api/auth/ vào IAM Service
        location /api/auth/ {
            proxy_pass http://iam_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        # Nếu ai đó gọi thẳng vào localhost không có /api/auth/, trả về thông báo
        location / {
            return 200 'API Gateway is Running!';
        }
    }
}